### PR TITLE
Add select nifti

### PR DESCRIPTION
**Pull request by natacha-beck**

### CODE REVIEW

**Comment by rdvincent** [comment]
I don't think it's a major problem, but your pull request seems to contain three extra commits - only the last one, 5b32fb1, seems to be relevant.

**Comment by rdvincent** [comment]
I am not completely sure, but I think you might need to rebase this branch on master. That might fix the issue.

**Comment by natacha-beck** [comment]
Yes sorry I will do that this afternoon and do an other PR. This one should
be closed.


Friday we (the CBRAIN team) will present our ongoing work since your cannot
be there can I show a demo of the Nifti viewer and talk about the fix for
the overlay ?

Natacha

2015-09-30 12:15 GMT-04:00 Robert D Vincent <notifications@github.com>:

**Comment by rdvincent** [comment]
Sounds great. I just realized that the zoom function was not working right
in the overlay, and I am fixing it.

**Comment by natacha-beck** [comment]
I just create a new PR. I will take a look to yours PR.

2015-09-30 12:52 GMT-04:00 Robert D Vincent <notifications@github.com>:

**Pull request closed without merging**
