### PR TITLE
Release 2.5.0 fix

### PR DESCRIPTION
**Pull request by natacha-beck**
This pull request contain the files for the release 2.5.0. It was necessary to add 'pako' under /lib in order to include this library in the minify version.

### CODE REVIEW

**Comment by natacha-beck** [comment]
@rdvincent Can you take a look to this one. It is the fix for the pako library.

**Comment by rdvincent** [comment]
@natacha-beck sorry, the previous code seemed to work ok - so does this just add pako.js so that it gets included in brainbrowser-*.min.js?

**Comment by natacha-beck** [comment]
Yes exactly, if I do not do that it do not go to the minify version so it
didn't work properly  when people use the minify version only.

**Comment by natacha-beck** [comment]
For example on our website.

**Pull request merged**
