### PR TITLE
fix mniobj Lines load when color is set per line

### PR DESCRIPTION
**Pull request by rentzso**
following when colour.flag is 1:
http://www.bic.mni.mcgill.ca/users/mishkin/mni_obj_format.pdf

### CODE REVIEW

**Comment by rdvincent** [comment]
Looks good to me.

**Comment by rentzso** [comment]
Thanks @rdvincent! 
When do you think this could be merged into master?

**Comment by natacha-beck** [comment]
@rentzso Everything seems good for me too, but I would like to have a file to play with it.

**Comment by rentzso** [comment]
You can check these two files:
[cube.obj.zip](https://github.com/aces/brainbrowser/files/794653/cube.obj.zip)
https://dl.dropboxusercontent.com/u/39271033/multiple_colors.obj

**Comment by natacha-beck** [comment]
Hi Renzo, as we start to have more developer on BrainBrowser and we will have more external collaborator soon, we decide to create a `dev` branch in order to work with a better git workflow. So can you please re-do your PR on the dev branch ? 
Once you create the new PR I will  merge, everything seems ok for me.

**Comment by rentzso** [comment]
Sure.

**Pull request closed without merging**
