### PR TITLE
Support for different image types

### PR DESCRIPTION
**Pull request by juanprietob**
Support for different image types. 
Function to change a pixel value on a volume. 
Addition of new demo and new sample images. One image is UCHAR another one is USHORT

### CODE REVIEW

**Comment by tsherif** [comment]
There's some very nice work here, @juanprietob!

We'll need to clean this PR up a bit before merging though. I'll look at things in more detail with the people taking over BrainBrowser over the next couple of days. As a start, here are some issues I've noticed:
1. 45c64ea56b57c052858b97d8ea88512bd28899d9 contains a file, `examples/models/structural2.mnc.header copy.gz`, that seems like it was added by accident.
2. Coding style: use of white space, variable names and variable declarations are inconsistent with the rest of the code base. See the [style guide](https://github.com/aces/brainbrowser/blob/master/STYLE.md).
3. I think it would be better to have an option in the original Volume Viewer demo to set intensity values, rather than having a whole new demo. Is there a reason you felt a new demo was needed?
4. The issue about edianness that I brought up in #215 hasn't been addressed. Basically, the problem is that if the raw data is created on a a machine with endianness different from the client machine on which BrainBrowser is running, the data will be misinterpreted. I think the solution would be to make converters like `minc2volume-viewer.js` add some header info indicating the byte ordering of the machine they run on. Then the Volume Viewer could use this info to ensure it's pulling bytes out in the right order.

**Comment by juanprietob** [comment]
I am cleaning up the code now. 
I created a new demo since it loads an image with USHORT type to test the functionality. 

I added two new images also. One has a color map generated by freesurfer, the other one is the corresponding T1 image. I added the parser for freesurfer color table. 
In the third window, both images are merged in the overlay (alpha level 1 for both, however this causes an issue with the brightness that has to be fixed). 

For the endianness issue. I have a c++ program that streams the content of the image (header, raw) using nifti files as input. I know the nifti reader takes care of the endianness so the data should be streamed in the same order regardless of the machine type. However, I am not sure how to address this issue in the front-end. Is this what is needed? http://stackoverflow.com/questions/7869752/javascript-typed-arrays-and-endianness

**Comment by juanprietob** [comment]
I have added a function to support bilinear interpolation. 
What do you think about my previous comment on the endianness issue? Could we discuss this a bit more?

**Comment by natacha-beck** [comment]
@juanprietob and @amallecourt, since the main developper of BrainBrowser left I'm the first one to take a look to your Pull Request.
I found some interesting features, but I cannot merge a huge Pull Request like this one in only one time.
Can you please follow the [Contributer Guidelines](https://github.com/aces/brainbrowser/blob/master/CONTRIBUTING.md), especially this three points:

* Create a separate, well-named branch for each contribution.
* Submit a pull request.
* Once finished with a contribution, do not push any more commits to the contribution branch. New commits will continue to appear in the pull request.

and if you do multiple different Pull Request, it will be really helpful for me.

**Pull request closed without merging**
